[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "ELt4FH2gH8RaZkYbvbbDjGkX8dPhGFdWnspM4w1fdjoY"
matching_engine = "DvYcaiBuaHgJFVjVd57JLM7ZMavzXvBezJwsvA46FJbH"

[programs.devnet]
vault = "ELt4FH2gH8RaZkYbvbbDjGkX8dPhGFdWnspM4w1fdjoY"
matching_engine = "DvYcaiBuaHgJFVjVd57JLM7ZMavzXvBezJwsvA46FJbH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'use cargo test + npm test'"

[test.validator]
url = "https://api.devnet.solana.com"

[workspace]
members = ["programs/vault", "programs/matching_engine"]
