[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "3S14CmmNb3bpGb68ukNFjFxxsLSpUijMfXaBJssBFRDb"
matching_engine = "G8MHBmzhfvRnhejot7XfeSFm3NC96uqm7VNduutM1J2K"

[programs.devnet]
vault = "3S14CmmNb3bpGb68ukNFjFxxsLSpUijMfXaBJssBFRDb"
matching_engine = "G8MHBmzhfvRnhejot7XfeSFm3NC96uqm7VNduutM1J2K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'use cargo test + npm test'"

[test.validator]
url = "https://api.devnet.solana.com"

[workspace]
members = ["programs/vault", "programs/matching_engine"]
